import { test, expect } from '../fixtures/auth';
import { randomUUID } from 'node:crypto';
test('identity assignments survive editing identity details', async ({ authenticatedPage: page, adminApi }) => {
  const name = `Identity-${randomUUID().slice(0, 8)}`;
  const targetResponse = await adminApi.post('/api/externalResource', { data: { name: `${name}-target` } });
  expect(targetResponse.ok()).toBeTruthy();
  const target = await targetResponse.json();
  await page.goto('/identities/create');
  await page.getByLabel('Name', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Create Identity', exact: true }).click();
  await expect(page).toHaveURL('/identities');
  const created = (await (await adminApi.get('/api/identity')).json()).find((item: any) => item.name === name);
  expect(created).toBeTruthy();
  await page.goto(`/identities/${created.id}/edit`);
  await page.getByRole('button', { name: 'Add Assignment', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Target Kind', { exact: true }).click();
  await page.getByRole('option', { name: /External/ }).click();
  await dialog.getByLabel('Target', { exact: true }).click();
  await page.getByRole('option', { name: `${name}-target`, exact: true }).click();
  await dialog.getByLabel('Role', { exact: true }).fill('Reader');
  await dialog.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByText('Role: Reader', { exact: true })).toBeVisible();
  await page.getByLabel('Notes', { exact: true }).fill('Updated identity details');
  await page.getByRole('button', { name: 'Save Changes', exact: true }).click();
  await expect(page).toHaveURL('/identities');
  await page.goto(`/identities/${created.id}/edit`);
  await expect(page.getByLabel('Notes', { exact: true })).toHaveValue('Updated identity details');
  await expect(page.getByText('Role: Reader', { exact: true })).toBeVisible();
  const saved = await (await adminApi.get(`/api/identity/${created.id}`)).json();
  expect(saved.assignments).toHaveLength(1);
  expect(saved.assignments[0].targetId).toBe(target.id);
  await page.goto('/identities');
  await page.getByRole('row').filter({ hasText: name }).getByRole('button').last().click();
  await page.getByRole('dialog').getByRole('button', { name: 'OK', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: name })).toBeHidden();
  expect((await adminApi.get(`/api/identity/${created.id}`)).status()).toBe(404);
  expect((await adminApi.get(`/api/externalResource/${target.id}`)).status()).toBe(200);
});
test('account grants survive saving account details', async ({ authenticatedPage: page, adminApi }) => {
  const name = `Account-${randomUUID().slice(0, 8)}`;
  const targetResponse = await adminApi.post('/api/externalResource', { data: { name: `${name}-target` } });
  expect(targetResponse.ok()).toBeTruthy();
  await page.goto('/accounts/create');
  await page.getByLabel('Target Kind', { exact: true }).click();
  await page.getByRole('option', { name: /External/ }).click();
  await page.getByLabel('Target', { exact: true }).click();
  await page.getByRole('option', { name: `${name}-target`, exact: true }).click();
  await page.getByLabel('Username', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Create Account', exact: true }).click();
  await expect(page).toHaveURL('/accounts');
  const created = (await (await adminApi.get('/api/account')).json()).find((item: any) => item.userName === name);
  expect(created).toBeTruthy();
  await page.goto(`/accounts/${created.id}/edit`);
  await page.getByRole('button', { name: 'Expand "Grants"', exact: true }).click();
  await page.getByRole('button', { name: 'Add Grant', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Database', { exact: true }).fill('Inventory');
  await dialog.getByLabel('Schema', { exact: true }).fill('dbo');
  await dialog.getByLabel('Privileges', { exact: true }).click();
  await page.getByRole('option').first().click();
  await page.keyboard.press('Escape');
  await dialog.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole('row').filter({ hasText: 'Inventory' })).toBeVisible();
  await page.getByLabel('Username', { exact: true }).fill(`${name}-saved`);
  await page.getByRole('button', { name: 'Save Changes', exact: true }).click();
  await expect(page).toHaveURL('/accounts');
  await page.goto(`/accounts/${created.id}/edit`);
  await expect(page.getByLabel('Username', { exact: true })).toHaveValue(`${name}-saved`);
  const saved = await (await adminApi.get(`/api/account/${created.id}`)).json();
  expect(saved.grants).toHaveLength(1);
  expect(saved.grants[0].database).toBe('Inventory');
  await page.goto('/accounts');
  await page.getByRole('row').filter({ hasText: `${name}-saved` }).getByRole('button').last().click();
  await page.getByRole('dialog').getByRole('button', { name: 'OK', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: `${name}-saved` })).toBeHidden();
  expect((await adminApi.get(`/api/account/${created.id}`)).status()).toBe(404);
});
