import { test, expect } from '../fixtures/auth';
import { randomUUID } from 'node:crypto';
test('application, instance and pipeline persist independently of details edits', async ({ authenticatedPage: page, adminApi }) => {
  const name = `App-${randomUUID().slice(0, 8)}`;
  await page.goto('/applications');
  await page.getByRole('button', { name: 'Create Application', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel(/^Name\*?$/).fill(name);
  await dialog.getByLabel('Version', { exact: true }).fill('1.0');
  await dialog.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page).toHaveURL(/\/applications\/[0-9a-f-]+$/);
  const id = page.url().split('/').pop();
  await page.getByRole('tab', { name: 'Instances', exact: true }).click();
  await page.getByRole('button', { name: 'Add Instance', exact: true }).click();
  await dialog.getByLabel('Environment*', { exact: true }).click();
  await page.getByRole('option', { name: 'UI test environment', exact: true }).click();
  await dialog.getByLabel('Version', { exact: true }).fill('instance-v1');
  await dialog.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page).toHaveURL(/\/instances\/[0-9a-f-]+$/);
  await expect(page.getByLabel('Version', { exact: true })).toHaveValue('instance-v1');
  const instanceUrl = page.url();
  const targetResponse = await adminApi.post('/api/externalResource', { data: { name: `${name}-dependency` } });
  expect(targetResponse.ok()).toBeTruthy();
  const target = await targetResponse.json();
  await page.reload();
  await page.getByRole('button', { name: 'Add Dependency', exact: true }).click();
  const draft = page.locator('tbody tr').filter({ has: page.getByRole('combobox') });
  await draft.getByRole('combobox').nth(0).click();
  await page.getByRole('option', { name: /External/ }).click();
  await draft.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: `${name}-dependency`, exact: true }).click();
  await draft.getByRole('button').first().click();
  await expect(page.getByRole('row').filter({ hasText: `${name}-dependency` })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('row').filter({ hasText: `${name}-dependency` })).toBeVisible();
  await page.goto(`/blast-radius?kind=External&id=${target.id}`);
  await expect(page.getByRole('link', { name: 'View Instance', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'View Instance', exact: true }).click();
  await expect(page).toHaveURL(instanceUrl);
  await page.goto(`/applications/${id}`);
  await page.getByRole('tab', { name: 'Pipelines', exact: true }).click();
  await page.getByRole('button', { name: 'Add Pipeline', exact: true }).click();
  await dialog.getByLabel('Name', { exact: true }).fill('Build pipeline');
  await dialog.getByLabel('Pipeline URI', { exact: true }).fill('https://example.test/build');
  await dialog.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole('row').filter({ hasText: 'Build pipeline' })).toBeVisible();
  await page.getByRole('tab', { name: 'Details', exact: true }).click();
  await page.getByLabel('Version', { exact: true }).fill('2.0');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByText('Application updated', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Version', { exact: true })).toHaveValue('2.0');
  const saved = await (await adminApi.get(`/api/application/${id}`)).json();
  expect(saved.instances).toHaveLength(1);
  expect(saved.instances[0].version).toBe('instance-v1');
  expect(saved.pipelines).toHaveLength(1);
  expect(saved.pipelines[0].name).toBe('Build pipeline');
  expect(saved.instances[0].dependencies).toHaveLength(1);
  expect(saved.instances[0].dependencies[0].targetId).toBe(target.id);
  await page.getByRole('tab', { name: 'History', exact: true }).click();
  const update = page.getByRole('row').filter({ hasText: 'Application Updated' }).first();
  await update.getByRole('button', { name: 'Undo', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'OK', exact: true }).click();
  await expect(page.getByText('Change reverted successfully', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Version', { exact: true })).toHaveValue('1.0');
  await page.getByRole('button', { name: 'Delete Application', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'OK', exact: true }).click();
  await expect(page).toHaveURL('/applications');
  expect((await adminApi.get(`/api/application/${id}`)).status()).toBe(404);
  expect((await adminApi.get(`/api/externalResource/${target.id}`)).status()).toBe(200);
});
