import { test, expect } from '../fixtures/auth';
import { randomUUID } from 'node:crypto';
test('application ownership assignment can be created, updated and deleted', async ({ authenticatedPage: page, adminApi }) => {
  const suffix = randomUUID().slice(0, 8);
  const appResponse = await adminApi.post('/api/application', { data: { name: `Owned-${suffix}` } });
  expect(appResponse.ok()).toBeTruthy();
  const app = await appResponse.json();
  expect((await adminApi.post('/api/position', { data: { name: `Owner-${suffix}` } })).ok()).toBeTruthy();
  expect((await adminApi.post('/api/responsibilityType', { data: { name: `Maintainer-${suffix}` } })).ok()).toBeTruthy();
  await page.goto(`/applications/${app.id}`);
  await page.getByRole('tab', { name: 'Ownership', exact: true }).click();
  await page.getByRole('button', { name: 'Add Assignment', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Position*', { exact: true }).click();
  await page.getByRole('option', { name: `Owner-${suffix}`, exact: true }).click();
  await dialog.getByLabel('Responsibility Type*', { exact: true }).click();
  await page.getByRole('option', { name: `Maintainer-${suffix}`, exact: true }).click();
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(dialog).toBeHidden();
  const row = page.getByRole('row').filter({ hasText: `Owner-${suffix}` });
  await expect(row).toBeVisible();
  await row.getByRole('button').first().click();
  await dialog.getByLabel('Notes', { exact: true }).fill('Ownership regression');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog).toBeHidden();
  await page.reload();
  await page.getByRole('tab', { name: 'Ownership', exact: true }).click();
  await expect(row).toContainText('Ownership regression');
  await row.getByRole('button').last().click();
  await dialog.getByRole('button', { name: 'OK', exact: true }).click();
  await expect(row).toBeHidden();
});
