//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    servicesAll(): Promise<ServiceManifest[]> {
        let url_ = this.baseUrl + "/api/Services";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesAll(_response);
        });
    }

    protected processServicesAll(response: Response): Promise<ServiceManifest[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ServiceManifest.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 204) {
            return response.text().then((_responseText) => {
            return throwException("No Content", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceManifest[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Created
     */
    servicesPOST(body: CreateServiceCommand | undefined): Promise<ServiceManifest> {
        let url_ = this.baseUrl + "/api/Services";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesPOST(_response);
        });
    }

    protected processServicesPOST(response: Response): Promise<ServiceManifest> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ServiceManifest.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceManifest>(null as any);
    }

    /**
     * @return OK
     */
    servicesGET(id: string): Promise<ServiceManifest> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesGET(_response);
        });
    }

    protected processServicesGET(response: Response): Promise<ServiceManifest> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ServiceManifest.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceManifest>(null as any);
    }

    /**
     * @param body (optional) 
     * @return No Content
     */
    servicesPUT(id: string, body: ServiceManifest | undefined): Promise<ServiceManifest> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesPUT(_response);
        });
    }

    protected processServicesPUT(response: Response): Promise<ServiceManifest> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            let result204: any = null;
            let resultData204 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result204 = ServiceManifest.fromJS(resultData204);
            return result204;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceManifest>(null as any);
    }

    /**
     * @return No Content
     */
    servicesDELETE(id: string): Promise<void> {
        let url_ = this.baseUrl + "/api/Services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processServicesDELETE(_response);
        });
    }

    protected processServicesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class CreateServiceCommand implements ICreateServiceCommand {
    name?: string | undefined;
    version?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
    author?: string | undefined;
    framework?: string | undefined;
    type?: CreateServiceCommandType;
    repositoryUri?: string | undefined;
    deploymentPipelines?: DeploymentPipeline[] | undefined;
    deployments?: Deployments[] | undefined;
    tags?: Tags[] | undefined;

    constructor(data?: ICreateServiceCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.version = _data["version"];
            this.description = _data["description"];
            this.notes = _data["notes"];
            this.author = _data["author"];
            this.framework = _data["framework"];
            this.type = _data["type"];
            this.repositoryUri = _data["repositoryUri"];
            if (Array.isArray(_data["deploymentPipelines"])) {
                this.deploymentPipelines = [] as any;
                for (let item of _data["deploymentPipelines"])
                    this.deploymentPipelines!.push(DeploymentPipeline.fromJS(item));
            }
            if (Array.isArray(_data["deployments"])) {
                this.deployments = [] as any;
                for (let item of _data["deployments"])
                    this.deployments!.push(Deployments.fromJS(item));
            }
            if (Array.isArray(_data["tags"])) {
                this.tags = [] as any;
                for (let item of _data["tags"])
                    this.tags!.push(Tags.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CreateServiceCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CreateServiceCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["version"] = this.version;
        data["description"] = this.description;
        data["notes"] = this.notes;
        data["author"] = this.author;
        data["framework"] = this.framework;
        data["type"] = this.type;
        data["repositoryUri"] = this.repositoryUri;
        if (Array.isArray(this.deploymentPipelines)) {
            data["deploymentPipelines"] = [];
            for (let item of this.deploymentPipelines)
                data["deploymentPipelines"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.deployments)) {
            data["deployments"] = [];
            for (let item of this.deployments)
                data["deployments"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.tags)) {
            data["tags"] = [];
            for (let item of this.tags)
                data["tags"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ICreateServiceCommand {
    name?: string | undefined;
    version?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
    author?: string | undefined;
    framework?: string | undefined;
    type?: CreateServiceCommandType;
    repositoryUri?: string | undefined;
    deploymentPipelines?: DeploymentPipeline[] | undefined;
    deployments?: Deployments[] | undefined;
    tags?: Tags[] | undefined;
}

export class DeploymentPipeline implements IDeploymentPipeline {
    name?: string | undefined;
    pipelineUri?: string | undefined;

    constructor(data?: IDeploymentPipeline) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.pipelineUri = _data["pipelineUri"];
        }
    }

    static fromJS(data: any): DeploymentPipeline {
        data = typeof data === 'object' ? data : {};
        let result = new DeploymentPipeline();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["pipelineUri"] = this.pipelineUri;
        return data;
    }
}

export interface IDeploymentPipeline {
    name?: string | undefined;
    pipelineUri?: string | undefined;
}

export class Deployments implements IDeployments {
    environmentName?: string | undefined;
    deploymentUri?: string | undefined;
    swaggerUri?: string | undefined;
    healthUri?: string | undefined;
    status?: DeploymentsStatus;

    constructor(data?: IDeployments) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.environmentName = _data["environmentName"];
            this.deploymentUri = _data["deploymentUri"];
            this.swaggerUri = _data["swaggerUri"];
            this.healthUri = _data["healthUri"];
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): Deployments {
        data = typeof data === 'object' ? data : {};
        let result = new Deployments();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["environmentName"] = this.environmentName;
        data["deploymentUri"] = this.deploymentUri;
        data["swaggerUri"] = this.swaggerUri;
        data["healthUri"] = this.healthUri;
        data["status"] = this.status;
        return data;
    }
}

export interface IDeployments {
    environmentName?: string | undefined;
    deploymentUri?: string | undefined;
    swaggerUri?: string | undefined;
    healthUri?: string | undefined;
    status?: DeploymentsStatus;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class ServiceManifest implements IServiceManifest {
    id?: string;
    name?: string | undefined;
    version?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
    author?: string | undefined;
    framework?: string | undefined;
    type?: ServiceManifestType;
    repositoryUri?: string | undefined;
    createdAt?: Date;
    updatedAt?: Date;
    deploymentPipelines?: DeploymentPipeline[] | undefined;
    deployments?: Deployments[] | undefined;
    tags?: Tags[] | undefined;

    constructor(data?: IServiceManifest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.version = _data["version"];
            this.description = _data["description"];
            this.notes = _data["notes"];
            this.author = _data["author"];
            this.framework = _data["framework"];
            this.type = _data["type"];
            this.repositoryUri = _data["repositoryUri"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
            if (Array.isArray(_data["deploymentPipelines"])) {
                this.deploymentPipelines = [] as any;
                for (let item of _data["deploymentPipelines"])
                    this.deploymentPipelines!.push(DeploymentPipeline.fromJS(item));
            }
            if (Array.isArray(_data["deployments"])) {
                this.deployments = [] as any;
                for (let item of _data["deployments"])
                    this.deployments!.push(Deployments.fromJS(item));
            }
            if (Array.isArray(_data["tags"])) {
                this.tags = [] as any;
                for (let item of _data["tags"])
                    this.tags!.push(Tags.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ServiceManifest {
        data = typeof data === 'object' ? data : {};
        let result = new ServiceManifest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["version"] = this.version;
        data["description"] = this.description;
        data["notes"] = this.notes;
        data["author"] = this.author;
        data["framework"] = this.framework;
        data["type"] = this.type;
        data["repositoryUri"] = this.repositoryUri;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        if (Array.isArray(this.deploymentPipelines)) {
            data["deploymentPipelines"] = [];
            for (let item of this.deploymentPipelines)
                data["deploymentPipelines"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.deployments)) {
            data["deployments"] = [];
            for (let item of this.deployments)
                data["deployments"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.tags)) {
            data["tags"] = [];
            for (let item of this.tags)
                data["tags"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IServiceManifest {
    id?: string;
    name?: string | undefined;
    version?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
    author?: string | undefined;
    framework?: string | undefined;
    type?: ServiceManifestType;
    repositoryUri?: string | undefined;
    createdAt?: Date;
    updatedAt?: Date;
    deploymentPipelines?: DeploymentPipeline[] | undefined;
    deployments?: Deployments[] | undefined;
    tags?: Tags[] | undefined;
}

export class Tags implements ITags {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    color?: string | undefined;

    constructor(data?: ITags) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.color = _data["color"];
        }
    }

    static fromJS(data: any): Tags {
        data = typeof data === 'object' ? data : {};
        let result = new Tags();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["color"] = this.color;
        return data;
    }
}

export interface ITags {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    color?: string | undefined;
}

export enum CreateServiceCommandType {
    WebApi = "WebApi",
    Worker = "Worker",
    FunctionApp = "FunctionApp",
    Database = "Database",
    Cache = "Cache",
    MessageBroker = "MessageBroker",
}

export enum DeploymentsStatus {
    Unknown = "Unknown",
    Running = "Running",
    Stopped = "Stopped",
    Degraded = "Degraded",
    Maintenance = "Maintenance",
    Failed = "Failed",
}

export enum ServiceManifestType {
    WebApi = "WebApi",
    Worker = "Worker",
    FunctionApp = "FunctionApp",
    Database = "Database",
    Cache = "Cache",
    MessageBroker = "MessageBroker",
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}